### PR TITLE
Highlight from all points

### PR DESCRIPTION
**Pull request by Golpette**
Just testing how to use these pull requests, and learn what they're actually for. My understanding is this:

I have branched from master to highlight_from_all_points and made some changes (mainly just that words are now highlighted from any point in them, with preference to across words, and secondly that I no longer highlight both across and down words if both exist. I now just prioritise across).

Now, let's say this may be a large change, or a controversial/speculative thing. I _think_ the point of a pull request is to inform you that I want you to pull and examine what I have done, offer me your suggestions and confirm if you think it is suitable to merge to master (or whatever "base" branch I specified above). 

If you liked it, I would then merge it. Possibly, there is an option that you can just merge it, since we both have equal right sin this project (but please don't just now! I'm just playing, and want to fix some other things before I merge)

Here's some reading:
https://help.github.com/articles/about-pull-requests/
https://help.github.com/articles/creating-a-pull-request/

### CODE REVIEW

**Comment by Golpette** [comment]
So here, you might point out that I haven't altered the back_space key function still, and that you would prefer this to be sorted before I perform a merge.

Actually: what do you think about the words being highlighted from any point? Do you prefer this to what is in the master branch (only highlight from start points). Maybe you think that the constant flcikering of green between words is distracting in the current implementation?

**Comment by Golpette** [comment]
I also believe I can keep pushing to this branch in the meantime and you can keep reviewing the updates. I'm going to push a non-modified version now

**Comment by AndrewRigg** [comment]
Yes I think it looks ace doing highlight from anywhere- it looked stranger without it.  In regards to flickering, I suggest we just use a gentler colour change so it's less distracting.  Well done Steve!

**Comment by AndrewRigg** [comment]
highlightinggrid

**Comment by AndrewRigg** [comment]
One small thing I did notice is that it throws an error when you try to select a black square.  Need to catch this condition.

**Pull request merged**
